Мелкие изменения

diff --git a/Final/pipeline b/Final/pipeline
--- a/Final/pipeline
+++ b/Final/pipeline
@@ -1,19 +1,29 @@
 pipeline {
     agent any
+    environment {
+        mynet = ' '
+    }
     stages {
+        stage ('Get neywork docker name') {
+           steps {
+              sh '''
+                 mynet=$(docker network ls | grep nginx | cut --delimiter=' ' -f 4)
+              '''
+           }
+        }
         stage ('Test') {
             agent {
                 dockerfile { filename 'dockerfile' 
-                             args '--net final_nginx-net'
+                            args '--net final_nginx-net'
                            }
             }
             steps {
                 sh '''
-                    make lint && make test
-                    if [ $? -ne 0 ];
-                        then
-                            echo "Test error"
-                            exit 1
+                make lint && make test
+                 if [ $? -ne 0 ];
+                    then
+                        echo "Test error"
+                        exit 1
                     fi
                 export GOPATH=$WORKSPACE/go
                 export PATH="$PATH:$(go env GOPATH)/bin"               
@@ -27,33 +37,34 @@ pipeline {
                 md5sum artifacts/word-cloud-generator
                 ls -l artifacts/
                 gzip -f ./artifacts/word-cloud-generator
+                cat static/version
                 '''
-            }
-        }
-        
-        stage ('Upload to nexus') {
-            steps {
-                nexusArtifactUploader (artifacts: [[artifactId: 'word-cloud-generator', 
-                classifier: '', file: 'artifacts/word-cloud-generator.gz', 
-                type: 'gz']], credentialsId: 'uploader', groupId: "$git_branch", 
-                nexusUrl: 'nexus:8081', nexusVersion: 'nexus3', protocol: 'http', 
-                repository: 'word-cloud-build', version: '1.$BUILD_NUMBER')
+                nexusArtifactUploader artifacts: [[artifactId: 'word-cloud-generator', classifier: '', file: 'artifacts/word-cloud-generator.gz', type: 'gz']], credentialsId: 'uploader', groupId: "$git_branch", nexusUrl: 'nexus:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'word-cloud-build', version: '1.$BUILD_NUMBER'
             }
         }
         stage('Testing') {
             agent {
                 dockerfile { filename 'alpine/alpinedockerfile' 
-                             args '-d --net final_nginx-net -p 8888:8888'
+                            args "-d --net final_nginx-net -p 8888:8888"
                            }
             }
             steps {
-                sh '''
-                 curl -u downloader:123 -X GET "http://nexus:8081/repository/word-cloud-build/$git_branch/word-cloud-generator/1.$BUILD_NUMBER/word-cloud-generator-1.$BUILD_NUMBER.gz" -o /opt/wordcloud/word-cloud-generator.gz
-                 gunzip -f /opt/wordcloud/word-cloud-generator.gz
-                 chmod +x /opt/wordcloud/word-cloud-generator
-                 /opt/wordcloud/word-cloud-generator &
-                 sleep 60
-                '''
+                withCredentials([usernamePassword(credentialsId: 'downloader', usernameVariable: 'nexus_user', passwordVariable: 'nexus_password')])
+                {
+                  sh '''
+                   curl -u ${nexus_user}:${nexus_password} -X GET "http://nexus:8081/repository/word-cloud-build/$git_branch/word-cloud-generator/1.$BUILD_NUMBER/word-cloud-generator-1.$BUILD_NUMBER.gz" -o /opt/wordcloud/word-cloud-generator.gz
+                   if [[ $? -ne 0 ]];
+                     then
+                       echo "File not found"
+                       exit 1
+                     else
+                       gunzip -f /opt/wordcloud/word-cloud-generator.gz
+                       chmod +x /opt/wordcloud/word-cloud-generator
+                       /opt/wordcloud/word-cloud-generator &
+                       sleep 180
+                       fi
+                  '''
+                }
             }
         }
     }
